// Code generated by sqlc. DO NOT EDIT.

package employee

import (
	"fmt"

	"github.com/google/uuid"
)

type JobPosition string

const (
	JobPositionProgrammer JobPosition = "programmer"
	JobPositionDesigner   JobPosition = "designer"
	JobPositionAdmin      JobPosition = "admin"
)

func (e *JobPosition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobPosition(s)
	case string:
		*e = JobPosition(s)
	default:
		return fmt.Errorf("unsupported scan type for JobPosition: %T", src)
	}
	return nil
}

type Employees struct {
	ID           int64       `json:"id"`
	EmployeeID   uuid.UUID   `json:"employeeID"`
	CompanyID    uuid.UUID   `json:"companyID"`
	Name         string      `json:"name"`
	JobPosition  JobPosition `json:"jobPosition"`
	Compensation string      `json:"compensation"`
}
