// Code generated by sqlc. DO NOT EDIT.

package company

import (
	"github.com/google/uuid"
)

type Companies struct {
	ID               int64     `json:"id"`
	CompanyID        uuid.UUID `json:"companyID"`
	CompanyAddressID uuid.UUID `json:"companyAddressID"`
	Name             string    `json:"name"`
	PhoneNumber      string    `json:"phoneNumber"`
}

type CompanyAddresses struct {
	ID                int64     `json:"id"`
	CompanyAddressID  uuid.UUID `json:"companyAddressID"`
	PostalCode        string    `json:"postalCode"`
	Street            string    `json:"street"`
	Number            string    `json:"number"`
	AddressComplement string    `json:"addressComplement"`
	Neighbourhood     string    `json:"neighbourhood"`
	City              string    `json:"city"`
	State             string    `json:"state"`
}
