// Code generated by sqlc. DO NOT EDIT.

package company

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Companies, error)
	CreateCompanyAddress(ctx context.Context, arg CreateCompanyAddressParams) (CompanyAddresses, error)
	DeleteCompany(ctx context.Context, companyID uuid.UUID) error
	GetCompanyByID(ctx context.Context, companyID uuid.UUID) (Companies, error)
	GetCompanyDetailsByID(ctx context.Context, companyID uuid.UUID) (GetCompanyDetailsByIDRow, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Companies, error)
	ListCompaniesDetails(ctx context.Context, arg ListCompaniesDetailsParams) ([]ListCompaniesDetailsRow, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Companies, error)
	UpdateCompanyAddress(ctx context.Context, arg UpdateCompanyAddressParams) (CompanyAddresses, error)
}

var _ Querier = (*Queries)(nil)
